"use client";
import React, { createContext, useContext, useState, useEffect } from "react";

export type Lang = "en" | "mr";

const translations = {
  en: {
    // Nav / Header
    appName: "SkillX",
    appSubtitle: "Maharashtra Labour Market Intelligence Platform",
    adminPortal: "Government Admin Dashboard",
    studentPortal: "Student Portal",
    langToggle: "मराठी",

    // Overview Cards
    dvetTrades: "DVET ITI Trades",
    mssdsCatalog: "MSSDS Course Catalog",
    activeJobs: "Active Job Postings",
    skillTerms: "Skill Dictionary Terms",
    unknownSkills: "Candidate Unknown Skills",
    avgAlignment: "Avg. Alignment Score",
    highDeficit: "High Deficit Districts",
    totalCourses: "Total Courses Indexed",

    // Status
    aligned: "ALIGNED",
    moderate: "MODERATE",
    highDeficitLabel: "HIGH DEFICIT",
    active: "ACTIVE",
    inactive: "INACTIVE",
    expired: "EXPIRED",

    // Engine Panel
    runEngines: "Run All Engines",
    running: "Running...",
    enginePanel: "4-Engine Pipeline Execution",
    estimatedTime: "Estimated Time Remaining",
    lastRun: "Last Pipeline Run",
    pipelineIdle: "Pipeline Idle — Click to Run",

    // Course Table
    courseAlignment: "Course Alignment Table",
    courseTitle: "Course Title",
    sector: "Sector",
    district: "District",
    score: "Alignment Score",
    missingSkills: "Missing Skills",
    bridgePack: "Bridge Pack",
    getBridgePack: "Get Bridge Pack",
    generating: "Generating...",
    fullyAligned: "Fully Aligned ✓",

    // GIS Map
    mapTitle: "Maharashtra District Skill Deficit Map",
    mapSubtitle: "Click a district to filter courses",

    // Bridge Pack Modal
    bridgePackTitle: "20-Hour Skill Bridge Pack",
    generatedBy: "Generated by",
    totalHours: "Total Hours",
    modules: "Modules",
    activities: "Activities",
    assessmentCriteria: "Assessment Criteria",
    toolsRequired: "Tools Required",
    close: "Close",

    // Skill Dictionary
    skillDictionary: "Skill Dictionary",
    standardTerms: "Standard Terms",
    candidateUnknown: "Candidate Unknown Skills",
    category: "Category",
    synonyms: "Synonyms",
    confidence: "Confidence",

    // Crawler
    triggerCrawl: "Trigger Full Crawl (85 Trades)",
    crawlerStatus: "Crawler Status",
    crawling: "Crawling...",
    crawlComplete: "Crawl Complete",

    // Student Portal
    studentTitle: "Find Your Right Course",
    studentSubtitle: "Discover ITI & MSSDS courses in your district and get a personalized skill bridge plan",
    selectDistrict: "Select Your District",
    selectSector: "Filter by Sector (Optional)",
    searchCourses: "Search Courses",
    courseRecommendations: "Course Recommendations",
    yourSkillGap: "Your Skill Gap",
    fullyMastered: "Fully Mastered Skills",
    skillsToLearn: "Skills to Learn",
    getYourBridgePack: "Get My 20-Hour Bridge Pack",
    nsqfLevel: "NSQF Level",
    duration: "Duration",
    months: "months",
    eligibility: "Eligibility",
    bridgePackReady: "Bridge Pack Ready",
    noCoursesFound: "No courses found for this district. Try another district or sector.",
  },
  mr: {
    // Nav / Header
    appName: "स्किलएक्स",
    appSubtitle: "महाराष्ट्र श्रमबाजार बुद्धिमत्ता व्यासपीठ",
    adminPortal: "सरकारी प्रशासक डॅशबोर्ड",
    studentPortal: "विद्यार्थी पोर्टल",
    langToggle: "English",

    // Overview Cards
    dvetTrades: "DVET ITI व्यवसाय",
    mssdsCatalog: "MSSDS अभ्यासक्रम सूची",
    activeJobs: "सक्रिय नोकरी जाहिराती",
    skillTerms: "कौशल्य शब्दकोश अटी",
    unknownSkills: "उमेदवार अज्ञात कौशल्ये",
    avgAlignment: "सरासरी संरेखन गुण",
    highDeficit: "उच्च तूट जिल्हे",
    totalCourses: "एकूण अनुक्रमित अभ्यासक्रम",

    // Status
    aligned: "संरेखित",
    moderate: "मध्यम",
    highDeficitLabel: "उच्च तूट",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    expired: "कालबाह्य",

    // Engine Panel
    runEngines: "सर्व इंजिन चालवा",
    running: "चालू आहे...",
    enginePanel: "४-इंजिन पाइपलाइन अंमलबजावणी",
    estimatedTime: "अनुमानित उर्वरित वेळ",
    lastRun: "शेवटची पाइपलाइन धाव",
    pipelineIdle: "पाइपलाइन बेकार — चालवण्यासाठी क्लिक करा",

    // Course Table
    courseAlignment: "अभ्यासक्रम संरेखन तक्ता",
    courseTitle: "अभ्यासक्रम शीर्षक",
    sector: "क्षेत्र",
    district: "जिल्हा",
    score: "संरेखन गुण",
    missingSkills: "अनुपस्थित कौशल्ये",
    bridgePack: "ब्रिज पॅक",
    getBridgePack: "ब्रिज पॅक मिळवा",
    generating: "तयार करत आहे...",
    fullyAligned: "पूर्णपणे संरेखित ✓",

    // GIS Map
    mapTitle: "महाराष्ट्र जिल्हा कौशल्य तूट नकाशा",
    mapSubtitle: "अभ्यासक्रम फिल्टर करण्यासाठी जिल्ह्यावर क्लिक करा",

    // Bridge Pack Modal
    bridgePackTitle: "२०-तास कौशल्य ब्रिज पॅक",
    generatedBy: "तयार केले",
    totalHours: "एकूण तास",
    modules: "मॉड्यूल",
    activities: "उपक्रम",
    assessmentCriteria: "मूल्यांकन निकष",
    toolsRequired: "आवश्यक साधने",
    close: "बंद करा",

    // Skill Dictionary
    skillDictionary: "कौशल्य शब्दकोश",
    standardTerms: "मानक अटी",
    candidateUnknown: "उमेदवार अज्ञात कौशल्ये",
    category: "श्रेणी",
    synonyms: "समानार्थी शब्द",
    confidence: "विश्वास",

    // Crawler
    triggerCrawl: "संपूर्ण क्रॉल सुरू करा (८५ व्यवसाय)",
    crawlerStatus: "क्रॉलर स्थिती",
    crawling: "क्रॉल करत आहे...",
    crawlComplete: "क्रॉल पूर्ण",

    // Student Portal
    studentTitle: "तुमचा योग्य अभ्यासक्रम शोधा",
    studentSubtitle: "तुमच्या जिल्ह्यातील ITI आणि MSSDS अभ्यासक्रम शोधा आणि वैयक्तिक कौशल्य ब्रिज योजना मिळवा",
    selectDistrict: "तुमचा जिल्हा निवडा",
    selectSector: "क्षेत्रानुसार फिल्टर करा (पर्यायी)",
    searchCourses: "अभ्यासक्रम शोधा",
    courseRecommendations: "अभ्यासक्रम शिफारसी",
    yourSkillGap: "तुमची कौशल्य तफावत",
    fullyMastered: "पूर्णपणे प्रभुत्व असलेली कौशल्ये",
    skillsToLearn: "शिकायची कौशल्ये",
    getYourBridgePack: "माझा २०-तास ब्रिज पॅक मिळवा",
    nsqfLevel: "NSQF स्तर",
    duration: "कालावधी",
    months: "महिने",
    eligibility: "पात्रता",
    bridgePackReady: "ब्रिज पॅक तयार",
    noCoursesFound: "या जिल्ह्यासाठी कोणतेही अभ्यासक्रम आढळले नाहीत. दुसरा जिल्हा किंवा क्षेत्र वापरून पहा.",
  },
};

type Translations = typeof translations.en;

interface LangContextType {
  lang: Lang;
  toggleLang: () => void;
  t: Translations;
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  toggleLang: () => {},
  t: translations.en,
});

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");

  useEffect(() => {
    const saved = localStorage.getItem("skillx_lang") as Lang | null;
    if (saved === "en" || saved === "mr") setLang(saved);
  }, []);

  const toggleLang = () => {
    const next: Lang = lang === "en" ? "mr" : "en";
    setLang(next);
    localStorage.setItem("skillx_lang", next);
  };

  return (
    <LangContext.Provider value={{ lang, toggleLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
