"use client";
import React, { createContext, useContext, useState, useEffect } from "react";

export type Lang = "en" | "mr" | "hi";

const translations = {
  en: {
    // Nav / Header
    appName: "SkillX",
    appSubtitle: "Maharashtra Labour Market Intelligence Platform",
    adminPortal: "Government Admin Dashboard",
    studentPortal: "Student Portal",
    langToggle: "Language",

    // Sidebar items
    navOverview: "Overview",
    navCourses: "Courses",
    navIndustry: "Industry Demand",
    navDistrictPlan: "District Plan",
    navDistricts: "Districts",
    navGaps: "Skill Gaps",
    navBridge: "Bridge Packs",
    navCrawler: "Data Crawler",

    // Government Intelligence
    industryDemand: "Industry Demand Intelligence",
    industryDemandSub: "Top skills demanded by Maharashtra's industrial sector",
    districtPlan: "District Skill Development Plan",
    districtPlanSub: "Generate actionable intervention plan for any district",
    skillGapSummary: "State-Wide Skill Gap Summary",
    traineeAtRisk: "Trainees At Risk",
    mismatchIndex: "Skill Mismatch Index",
    criticalDeficit: "Critical Deficit Courses",
    interventionSimulator: "What-If Simulator",
    generatePlan: "Generate Plan",
    viewDistrictPlan: "View District Plan →",

    // Overview Cards & Highlights
    dvetTrades: "DVET ITI Trades",
    mssdsCatalog: "MSSDS Course Master",
    activeJobs: "Active Job Postings",
    skillTerms: "Skill Dictionary Terms",
    unknownSkills: "Candidate Unknown Skills",
    avgAlignment: "Avg. Alignment Score",
    highDeficit: "High Deficit Districts",
    totalCourses: "Total Courses Indexed",

    // Status
    aligned: "ALIGNED",
    moderate: "MODERATE",
    highDeficitLabel: "HIGH DEFICIT",
    active: "ACTIVE",
    inactive: "INACTIVE",
    expired: "EXPIRED",

    // Engine & Batch Panel
    runEngines: "Run All Engines",
    running: "Running...",
    enginePanel: "4-Engine Pipeline Execution",
    estimatedTime: "Estimated Time Remaining",
    lastRun: "Last Pipeline Run",
    pipelineIdle: "Pipeline Idle — Click to Run",
    batchCatalogueTitle: "Course Catalogue Analysis",
    remainingCourses: "courses remaining in catalogue",
    analysedOf: "analysed",
    analyseNextBatch: "⚡ Analyse Next 50 Courses",
    analysingBatch: "⚙ Analysing 50 Courses...",

    // Course Table
    courseAlignment: "Course Alignment Table",
    courseTitle: "Course Title",
    sector: "Sector",
    district: "District",
    score: "Alignment Score",
    missingSkills: "Missing Skills",
    bridgePack: "Bridge Pack",
    getBridgePack: "Get Bridge Pack",
    generating: "Generating...",
    fullyAligned: "Fully Aligned ✓",
    searchPlaceholder: "Search course title, trade or sector...",

    // GIS Map
    mapTitle: "Maharashtra District Skill Deficit Map",
    mapSubtitle: "Click a district to filter courses",

    // Bridge Pack Modal
    bridgePackTitle: "20-Hour Skill Bridge Pack",
    generatedBy: "Generated by",
    totalHours: "Total Hours",
    modules: "Modules",
    activities: "Activities",
    assessmentCriteria: "Assessment Criteria",
    toolsRequired: "Tools Required",
    close: "Close",

    // Skill Dictionary
    skillDictionary: "Skill Dictionary",
    standardTerms: "Standard Terms",
    candidateUnknown: "Candidate Unknown Skills",
    category: "Category",
    synonyms: "Synonyms",
    confidence: "Confidence",

    // Student Portal
    studentTitle: "Find Your Right Course",
    studentSubtitle: "Discover ITI & MSSDS courses in your district and get a personalized skill bridge plan",
    selectDistrict: "Select Your District",
    selectSector: "Filter by Sector (Optional)",
    searchCourses: "Search Courses",
    courseRecommendations: "Course Recommendations",
    yourSkillGap: "Your Skill Gap",
    fullyMastered: "Fully Mastered Skills",
    skillsToLearn: "Skills to Learn",
    getYourBridgePack: "Get My 20-Hour Bridge Pack",
    nsqfLevel: "NSQF Level",
    duration: "Duration",
    months: "months",
    eligibility: "Eligibility",
    bridgePackReady: "Bridge Pack Ready",
    noCoursesFound: "No courses found for this district. Try another district or sector.",
  },
  mr: {
    // Nav / Header
    appName: "स्किलएक्स",
    appSubtitle: "महाराष्ट्र श्रमबाजार बुद्धिमत्ता व्यासपीठ",
    adminPortal: "सरकारी प्रशासक डॅशबोर्ड",
    studentPortal: "विद्यार्थी पोर्टल",
    langToggle: "भाषा",

    // Sidebar items
    navOverview: "पूर्वावलोकन",
    navCourses: "अभ्यासक्रम",
    navIndustry: "उद्योग मागणी",
    navDistrictPlan: "जिल्हा योजना",
    navDistricts: "जिल्हे",
    navGaps: "कौशल्य तफावत",
    navBridge: "ब्रिज पॅक",
    navCrawler: "डेटा क्रॉलर",

    // Government Intelligence
    industryDemand: "उद्योग मागणी बुद्धिमत्ता",
    industryDemandSub: "महाराष्ट्रातील औद्योगिक क्षेत्राने मागणी केलेली शीर्ष कौशल्ये",
    districtPlan: "जिल्हा कौशल्य विकास योजना",
    districtPlanSub: "कोणत्याही जिल्ह्यासाठी कृती योजना तयार करा",
    skillGapSummary: "राज्यव्यापी कौशल्य तफावत सारांश",
    traineeAtRisk: "धोक्यात असलेले प्रशिक्षणार्थी",
    mismatchIndex: "कौशल्य जुळवणी निर्देशांक",
    criticalDeficit: "गंभीर तूट अभ्यासक्रम",
    interventionSimulator: "काय-होईल सिम्युलेटर",
    generatePlan: "योजना तयार करा",
    viewDistrictPlan: "जिल्हा योजना पहा →",

    // Overview Cards & Highlights
    dvetTrades: "DVET ITI व्यवसाय",
    mssdsCatalog: "MSSDS अभ्यासक्रम मास्टर",
    activeJobs: "सक्रिय नोकरी जाहिराती",
    skillTerms: "कौशल्य शब्दकोश शब्द",
    unknownSkills: "उमेदवार अज्ञात कौशल्ये",
    avgAlignment: "सरासरी संरेखन गुण",
    highDeficit: "उच्च तूट जिल्हे",
    totalCourses: "एकूण अनुक्रमित अभ्यासक्रम",

    // Status
    aligned: "संरेखित",
    moderate: "मध्यम",
    highDeficitLabel: "उच्च तूट",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    expired: "कालबाह्य",

    // Engine & Batch Panel
    runEngines: "सर्व इंजिन चालवा",
    running: "चालू आहे...",
    enginePanel: "४-इंजिन पाइपलाइन अंमलबजावणी",
    estimatedTime: "अनुमानित उर्वरित वेळ",
    lastRun: "शेवटची पाइपलाइन धाव",
    pipelineIdle: "पाइपलाइन निष्क्रिय — चालवण्यासाठी क्लिक करा",
    batchCatalogueTitle: "अभ्यासक्रम सूची विश्लेषण",
    remainingCourses: "सूचीमध्ये उरलेले अभ्यासक्रम",
    analysedOf: "विश्लेषण केले",
    analyseNextBatch: "⚡ पुढील ५० अभ्यासक्रमांचे विश्लेषण करा",
    analysingBatch: "⚙ ५० अभ्यासक्रमांचे विश्लेषण करत आहे...",

    // Course Table
    courseAlignment: "अभ्यासक्रम संरेखन तक्ता",
    courseTitle: "अभ्यासक्रम शीर्षक",
    sector: "क्षेत्र",
    district: "जिल्हा",
    score: "संरेखन गुण",
    missingSkills: "अनुपस्थित कौशल्ये",
    bridgePack: "ब्रिज पॅक",
    getBridgePack: "ब्रिज पॅक मिळवा",
    generating: "तयार करत आहे...",
    fullyAligned: "पूर्णपणे संरेखित ✓",
    searchPlaceholder: "अभ्यासक्रम शीर्षक, ट्रेड किंवा क्षेत्र शोधा...",

    // GIS Map
    mapTitle: "महाराष्ट्र जिल्हा कौशल्य तूट नकाशा",
    mapSubtitle: "अभ्यासक्रम फिल्टर करण्यासाठी जिल्ह्यावर क्लिक करा",

    // Bridge Pack Modal
    bridgePackTitle: "२०-तास कौशल्य ब्रिज पॅक",
    generatedBy: "तयार केले",
    totalHours: "एकूण तास",
    modules: "मॉड्यूल",
    activities: "उपक्रम",
    assessmentCriteria: "मूल्यांकन निकष",
    toolsRequired: "आवश्यक साधने",
    close: "बंद करा",

    // Skill Dictionary
    skillDictionary: "कौशल्य शब्दकोश",
    standardTerms: "मानक शब्द",
    candidateUnknown: "उमेदवार अज्ञात कौशल्ये",
    category: "श्रेणी",
    synonyms: "समानार्थी शब्द",
    confidence: "विश्वास",

    // Student Portal
    studentTitle: "तुमचा योग्य अभ्यासक्रम शोधा",
    studentSubtitle: "तुमच्या जिल्ह्यातील ITI आणि MSSDS अभ्यासक्रम शोधा आणि वैयक्तिक कौशल्य ब्रिज योजना मिळवा",
    selectDistrict: "तुमचा जिल्हा निवडा",
    selectSector: "क्षेत्रानुसार फिल्टर करा (पर्यायी)",
    searchCourses: "अभ्यासक्रम शोधा",
    courseRecommendations: "अभ्यासक्रम शिफारसी",
    yourSkillGap: "तुमची कौशल्य तफावत",
    fullyMastered: "पूर्णपणे प्रभुत्व असलेली कौशल्ये",
    skillsToLearn: "शिकायची कौशल्ये",
    getYourBridgePack: "माझा २०-तास ब्रिज पॅक मिळवा",
    nsqfLevel: "NSQF स्तर",
    duration: "कालावधी",
    months: "महिने",
    eligibility: "पात्रता",
    bridgePackReady: "ब्रिज पॅक तयार",
    noCoursesFound: "या जिल्ह्यासाठी कोणतेही अभ्यासक्रम आढळले नाहीत. दुसरा जिल्हा किंवा क्षेत्र वापरून पहा.",
  },
  hi: {
    // Nav / Header
    appName: "स्किलएक्स",
    appSubtitle: "महाराष्ट्र श्रम बाजार बुद्धिमत्ता मंच",
    adminPortal: "सरकारी प्रशासक डैशबोर्ड",
    studentPortal: "छात्र पोर्टल",
    langToggle: "भाषा",

    // Sidebar items
    navOverview: "अवलोकन",
    navCourses: "पाठ्यक्रम",
    navIndustry: "उद्योग मांग",
    navDistrictPlan: "जिला योजना",
    navDistricts: "जिले",
    navGaps: "कौशल अंतर",
    navBridge: "ब्रिज पैक",
    navCrawler: "डेटा क्रॉलर",

    // Government Intelligence
    industryDemand: "उद्योग मांग बुद्धिमत्ता",
    industryDemandSub: "महाराष्ट्र के औद्योगिक क्षेत्र द्वारा माँगे गए शीर्ष कौशल",
    districtPlan: "जिला कौशल विकास योजना",
    districtPlanSub: "किसी भी जिले के लिए कार्य योजना बनाएं",
    skillGapSummary: "राज्यव्यापी कौशल अंतर सारांश",
    traineeAtRisk: "जोखिम में प्रशिक्षु",
    mismatchIndex: "कौशल बेमेल सूचकांक",
    criticalDeficit: "गंभीर घाटे वाले पाठ्यक्रम",
    interventionSimulator: "क्या-होगा सिम्युलेटर",
    generatePlan: "योजना बनाएं",
    viewDistrictPlan: "जिला योजना देखें →",

    // Overview Cards & Highlights
    dvetTrades: "DVET ITI ट्रेड्स",
    mssdsCatalog: "MSSDS पाठ्यक्रम मास्टर",
    activeJobs: "सक्रिय नौकरी विज्ञापन",
    skillTerms: "कौशल शब्दकोश पद",
    unknownSkills: "अज्ञात कौशल",
    avgAlignment: "औसत संरेखण स्कोर",
    highDeficit: "उच्च घाटा वाले जिले",
    totalCourses: "कुल अनुक्रमित पाठ्यक्रम",

    // Status
    aligned: "संरेखित",
    moderate: "मध्यम",
    highDeficitLabel: "उच्च घाटा",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    expired: "समाप्त",

    // Engine & Batch Panel
    runEngines: "सभी इंजन चलाएं",
    running: "चल रहा है...",
    enginePanel: "4-इंजन पाइपलाइन निष्पादन",
    estimatedTime: "अनुमानित शेष समय",
    lastRun: "अंतिम पाइपलाइन रन",
    pipelineIdle: "पाइपलाइन निष्क्रिय — चलाने के लिए क्लिक करें",
    batchCatalogueTitle: "पाठ्यक्रम कैटलॉग विश्लेषण",
    remainingCourses: "कैटलॉग में शेष पाठ्यक्रम",
    analysedOf: "विश्लेषण किया गया",
    analyseNextBatch: "⚡ अगले 50 पाठ्यक्रमों का विश्लेषण करें",
    analysingBatch: "⚙ 50 पाठ्यक्रमों का विश्लेषण जारी...",

    // Course Table
    courseAlignment: "पाठ्यक्रम संरेखण तालिका",
    courseTitle: "पाठ्यक्रम शीर्षक",
    sector: "क्षेत्र",
    district: "जिला",
    score: "संरेखण स्कोर",
    missingSkills: "अनुपस्थित कौशल",
    bridgePack: "ब्रिज पैक",
    getBridgePack: "ब्रिज पैक प्राप्त करें",
    generating: "जनरेट हो रहा है...",
    fullyAligned: "पूर्णतः संरेखित ✓",
    searchPlaceholder: "पाठ्यक्रम शीर्षक, ट्रेड या क्षेत्र खोजें...",

    // GIS Map
    mapTitle: "महाराष्ट्र जिला कौशल घाटा मानचित्र",
    mapSubtitle: "पाठ्यक्रम फ़िल्टर करने के लिए किसी जिले पर क्लिक करें",

    // Bridge Pack Modal
    bridgePackTitle: "20-घंटे का कौशल ब्रिज पैक",
    generatedBy: "द्वारा जनरेट किया गया",
    totalHours: "कुल घंटे",
    modules: "मॉड्यूल",
    activities: "गतिविधियां",
    assessmentCriteria: "मूल्यांकन मानदंड",
    toolsRequired: "आवश्यक उपकरण",
    close: "बंद करें",

    // Skill Dictionary
    skillDictionary: "कौशल शब्दकोश",
    standardTerms: "मानक शब्द",
    candidateUnknown: "अज्ञात कौशल",
    category: "श्रेणी",
    synonyms: "पर्यायवाची",
    confidence: "विश्वास",

    // Student Portal
    studentTitle: "अपना सही पाठ्यक्रम खोजें",
    studentSubtitle: "अपने जिले में ITI और MSSDS पाठ्यक्रम खोजें और व्यक्तिगत कौशल ब्रिज योजना प्राप्त करें",
    selectDistrict: "अपना जिला चुनें",
    selectSector: "क्षेत्र के अनुसार फ़िल्टर करें (वैकल्पिक)",
    searchCourses: "पाठ्यक्रम खोजें",
    courseRecommendations: "पाठ्यक्रम सिफारिशें",
    yourSkillGap: "आपका कौशल अंतर",
    fullyMastered: "पूर्णतः महारत हासिल कौशल",
    skillsToLearn: "सीखने योग्य कौशल",
    getYourBridgePack: "मेरा 20-घंटे का ब्रिज पैक प्राप्त करें",
    nsqfLevel: "NSQF स्तर",
    duration: "अवधि",
    months: "महीने",
    eligibility: "पात्रता",
    bridgePackReady: "ब्रिज पैक तैयार",
    noCoursesFound: "इस जिले के लिए कोई पाठ्यक्रम नहीं मिला। कृपया दूसरा जिला या क्षेत्र चुनें।",
  },
};

type Translations = typeof translations.en;

interface LangContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  toggleLang: () => void;
  t: Translations;
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  setLang: () => {},
  toggleLang: () => {},
  t: translations.en,
});

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const saved = localStorage.getItem("skillx_lang") as Lang | null;
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if (saved === "en" || saved === "mr" || saved === "hi") setLangState(saved);
  }, []);

  const setLang = (next: Lang) => {
    setLangState(next);
    localStorage.setItem("skillx_lang", next);
  };

  const toggleLang = () => {
    const next: Lang = lang === "en" ? "mr" : lang === "mr" ? "hi" : "en";
    setLang(next);
  };

  return (
    <LangContext.Provider value={{ lang, setLang, toggleLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
